---

    - name: Print nvidia_use_open
      ansible.builtin.debug:
        msg: "nvidia_use_open: '{{ nvidia_use_open }}'."

    - name: Install the specified version of kernel packages with dnf
      dnf:
        name:
          - python3-dnf-plugin-versionlock
          - kernel-devel-{{ target_kernel }}
          - kernel-headers-{{ target_kernel }}
          - kernel-core-{{ target_kernel }}
        state: present

    - name: Prevent kernel packages from being updated
      community.general.dnf_versionlock:
        name:
          - kernel-devel-{{ target_kernel }}
          - kernel-headers-{{ target_kernel }}
          - kernel-core-{{ target_kernel }}
        state: present



    # We are following: # https://github.com/NVIDIA/yum-packaging-precompiled-kmod


    - name: Ensure git and other tools are installed
      ansible.builtin.dnf:
        name:
          - git
          - rpm-build
          - gcc-c++
        state: present

    - name: Clone NVIDIA yum-packaging-precompiled-kmod (rhel9 branch)
      ansible.builtin.git:
        repo: "{{ nvidia_precompile_repo }}"
        dest: "{{ nvidia_work_folder }}"
        version: "{{ nvidia_precompile_repo_branch }}"
        force: yes



    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ nvidia_work_folder }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}"
        - BUILD
        - BUILDROOT
        - RPMS
        - SRPMS
        - SOURCES
        - SPECS

    - name: prepare closed driver
      when: not ( (nvidia_use_open | default(false)) | bool )
      block:

      - name: Download NVIDIA runfile
        ansible.builtin.get_url:
          url: "{{ nvidia_runfile_url }}"
          dest: "{{ nvidia_work_folder }}/{{ nvidia_runfile_url | basename }}"
          mode: '0755'

      - name: Extract NVIDIA installer
        ansible.builtin.command: "sh NVIDIA-Linux-{{ nvidia_arch }}-{{ nvidia_driver_version }}.run --extract-only --target tmp"
        args:
          chdir: "{{ nvidia_work_folder }}"
          creates: "{{ nvidia_work_folder }}/tmp"

      - name: Move extracted kernel directory
        ansible.builtin.command: "mv tmp/kernel nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}/"
        args:
          chdir: "{{ nvidia_work_folder }}"
          creates: "{{ nvidia_work_folder }}/nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}/kernel"


      - name: Create NVIDIA kmod tarball
        ansible.builtin.command: "tar -cJf SOURCES/nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}.tar.xz nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}"
        args:
          chdir: "{{ nvidia_work_folder }}"
          creates: "{{ nvidia_work_folder }}/SOURCES/nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}.tar.xz"

    - name: prepare open driver
      when:  (nvidia_use_open | default(false)) | bool
      block:

      - name: Set fake kernel file
        ansible.builtin.lineinfile:
          path: /etc/fake-kernel
          state: present
          create: true
          # e.g. "5.14.0-570.44.1.el9_6.x86_64"
          line: "{{ target_kernel }}"
          owner: root
          group: root
          mode: '0644'

      - name: Move uname to uname-bin
        ansible.builtin.command:
          cmd: mv /usr/bin/uname /usr/bin/uname-bin
          creates: /usr/bin/uname-bin

      - name: Copy uname wrapper
        ansible.builtin.copy:
          src: files/uname-wrapper.sh
          dest: /usr/bin/uname
          owner: root
          group: root
          mode: u=rwx,g=rx,o=rx

      - name: Clone NVIDIA/open-gpu-kernel-modules.git
        ansible.builtin.git:
          repo: "https://github.com/NVIDIA/open-gpu-kernel-modules.git"
          dest: "{{ nvidia_work_folder }}/open-gpu-kernel-modules/"
          version: "{{ nvidia_driver_version }}"
          force: yes

      - name: Create NVIDIA open kmod tarball
        ansible.builtin.command:
          cmd: "tar -cJf SOURCES/nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}.tar.xz --exclude open-gpu-kernel-modules/.git/\\* open-gpu-kernel-modules/"
        args:
          chdir: "{{ nvidia_work_folder }}"
          creates: "{{ nvidia_work_folder }}/SOURCES/nvidia-kmod-{{ nvidia_driver_version }}-{{ nvidia_arch }}.tar.xz"


      - name: "Replace %setup folder"
        ansible.builtin.replace:
          path: "{{ nvidia_work_folder }}/kmod-nvidia.spec"
          regexp: '^\s*%setup -q -n %\{kmod_source_name\}\s*$'
          replace: '%setup -q -n open-gpu-kernel-modules'
          backup: yes

      - name: Comment out 'cd kernel' right after %build
        ansible.builtin.replace:
          path: "{{ nvidia_work_folder }}/kmod-nvidia.spec"
          regexp: '^(%build[^\n]*\n)(\s*)cd kernel(\s*)$'
          replace: '\1\2# cd kernel\3'
          backup: yes

      - name: Replace make_build line right after the specific %if
        ansible.builtin.replace:
          path: "{{ nvidia_work_folder }}/kmod-nvidia.spec"
          regexp: '^(%if 0%\{\?hsm\} == 0 \|\| 0%\{\?hsm\} == 1[^\n]*\n)(\s*)%\{make_build\}\s+SYSSRC=\$\{KERNEL_SOURCES\}\s+SYSOUT=\$\{KERNEL_OUTPUT\}\s*$'
          replace: '\1\2%{make_build}\n\2cd kernel-open'
          backup: yes

      - name: Replace all occurrences of 'cd kernel' with 'cd kernel-open' unless already -open
        ansible.builtin.replace:
          path: "{{ nvidia_work_folder }}/kmod-nvidia.spec"
          regexp: '\bcd\s+kernel\b(?!-open)'
          replace: 'cd kernel-open'
          backup: yes


    - name: Comment out install lines in kmod-nvidia.spec
      ansible.builtin.shell: >-
        sed '/^install .*\.sig %{buildroot}/ s/^/#/' kmod-nvidia.spec
        | sed 's/^Epoch:[[:space:]]*3$/Epoch:          %{epoch}/'
        | sed 's/^Release:[[:space:]]*3%{kmod_dist}$/Release:        %{releasenumber}%{kmod_dist}/'
        > SPECS/kmod-nvidia.spec
      args:
        chdir: "{{ nvidia_work_folder }}"
        creates: "{{ nvidia_work_folder }}/SPECS/kmod-nvidia.spec"

    - name: Create an empty, executable hsm_wrapper_script
      ansible.builtin.file:
        path: "{{ nvidia_work_folder }}/SOURCES/hsm_wrapper_script"
        state: touch
        mode: '0755'

    - name: Build kmod NVIDIA RPM
      ansible.builtin.command: >
        rpmbuild
        --define "%_topdir {{ nvidia_work_folder }}"
        --define "debug_package %{nil}"
        --define "kernel {{ kernel_version }}"
        --define "kernel_release {{ kernel_release }}"
        --define "kernel_dist .{{ kernel_dist }}"
        --define "driver {{ nvidia_driver_version }}"
        --define "epoch {{ nvidia_epoch }}"
        --define "driver_branch latest"
        --define "hsm 1"
        --define "hsm_wrapper_script hsm_wrapper_script"
        --define "releasenumber {{ nvidia_releasenumber }}"
        -v -bb SPECS/kmod-nvidia.spec
      args:
        chdir: "{{ nvidia_work_folder }}"
        creates: "{{ nvidia_rpm }}"
